name: Deploy to Testing

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release (must match tag in DockerHub)
        required: true
  workflow_run:
    workflows: [ 'Docker Build Latest Commit' ]
    types: [ completed ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/setup-kubectl@v1
    - name: Authenticate with kubernetes
      run: |
        mkdir -p ${HOME}/.kube/certs/cluster
        echo ${{ secrets.KUBERNETES_CA }} | base64 -d > ${HOME}/.kube/certs/cluster/k8s-ca.crt
        kubectl config set-cluster cluster --certificate-authority=${HOME}/.kube/certs/cluster/k8s-ca.crt --server=https://hatcher.kubernetes.lib.umich.edu
        kubectl config set-credentials default --token=${{ secrets.KUBERNETES_TOKEN }}
        kubectl config set-context default --cluster=cluster --user=default --namespace=mattlach-github-actions
        kubectl config use-context default
    - name: Automatic Deploy
      if: ${{ github.event_name == 'workflow_run' }}
      run: kubectl set image deployment web web=mlibrary/mattlach-phineas-testing-actions:testing-${{ github.sha }}
    - name: Manual Deploy
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: kubectl set image deployment web web=mlibrary/mattlach-phineas-testing-actions:${{ github.event.inputs.tag }}
