name: Docker Tag Latest Release

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Clone latest repository
      uses: actions/checkout@v2
    - name: Tag latest release in DockerHub
      run: |
        docker pull mlibrary/mattlach-phineas-testing-actions:testing-${{ github.sha }}
        docker tag mattlach-phineas-testing-actions:testing-${{ github.sha }} mlibrary/mattlach-phineas-testing-actions:${{ github.event.release.tag_name }}
        docker tag mattlach-phineas-testing-actions:testing-${{ github.sha }} mlibrary/mattlach-phineas-testing-actions:latest
    - name: Update DockerHub README
      uses: peter-evans/dockerhub-description@v2
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        DOCKERHUB_REPOSITORY: mlibrary/mattlach-phineas-testing-actions
