name: Docker Build Latest Commit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build container image and push to DockerHub
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: 'mlibrary/mattlach-phineas-testing-actions:testing-latest,mlibrary/mattlach-phineas-testing-actions:testing-${{ github.sha }}'
    - name: Image digest
      run: |
        echo '${{ steps.docker_build.outputs.digest }}'
