name: Deploy

on:
  workflow_dispatch:
    inputs:
      release:
        description: Release
        required: true
      destination:
        description: 'Type "production" to deploy to production'
        default: staging

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Deploy ${{ github.event.inputs.release }} into ${{ github.event.inputs.destination }}"
